sudo: required

services:
  - docker

lenguage: generic

before_install:
  - docker build -t felix/dk-react -f Dockerfile.dev .

script:
  - docker run -e CI=true felix/dk-react yarn run test -- --coverage
